import { ConfigProvider } from 'antd';
import { customTheme } from '@/hooks/useDeviceType';
import type { Metadata } from "next";
// import { fetchCsrfToken } from '@/utils/url';
import { Nunito, Montserrat, Poppins } from 'next/font/google';

import "./globals.css";
import './globals.scss'
import Header from '@/common/components/Header/Header';
import Navbar from '@/common/components/Sst/Navbar/Navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-nunito',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-montserrat',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: '--font-poppins',
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const csrfToken = await fetchCsrfToken();

  return (
    <html lang="en" className={`${nunito.className} ${montserrat.className} ${poppins.className}`}>
      <head>
        {/* <meta name="csrf-token" content={csrfToken || ''} /> */}
      </head>
      <body>
        <ConfigProvider theme={customTheme}>
          <Header>
            <Navbar />
          </Header>
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
