import { ConfigProvider } from 'antd';
import type { Metadata } from "next";

import { fontVariables } from '@libs/fonts';
import { customTheme } from '@hooks/useDeviceType';

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={fontVariables}>
      <head>
        {/* <meta name="csrf-token" content={csrfToken || ''} /> */}
      </head>
      <body>
        <ConfigProvider theme={customTheme}>
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
